apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: experiment-subscriber
  name: experiment-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: experiment-subscriber
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/mqtt-experiment-default: "true"
        io.kompose.service: experiment-subscriber
    spec:
      containers:
        - image: experiment-subscriber
          name: experiment-subscriber
          resources: {}
      restartPolicy: Always
status: {}
